[package]
authors = ["Another one bytes the Rust"]
name = "tile-resource-mapper-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
robotics_lib = {version = "0.1.19", registry = "kellnr"}